name: Android Release Build (Signed with debug keystore)

on:
  workflow_dispatch:   # Permet de lancer manuellement depuis l’onglet Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère ton code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure Java (nécessaire pour Android Gradle)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Configure le cache Gradle (accélère les builds)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Donne les droits d’exécution à gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 5. Lance la compilation en mode release
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # 6. Sauvegarde l’APK généré en artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CommandePompe-Release-APK
          path: app/build/outputs/apk/release/*.apk
